CREATE TABLE COFFEE (ID INT, NAME VARCHAR(128), PRICE INT, AVAILABLE BOOLEAN);
INSERT INTO COFFEE VALUES (1, 'americano', 1000, TRUE);
INSERT INTO COFFEE VALUES (2, 'cafe latte', 1500, TRUE);
INSERT INTO COFFEE VALUES (3, 'cafe mocha', 1500, TRUE);